server:
  port: 9999

spring:
  profiles:
    active:
      - default

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  datasource:
    url: jdbc:mariadb://localhost:3306/skccproject
    driver-class-name: org.mariadb.jdbc.Driver
    username: skccproject
    password: skccproject

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update