apiVersion: v1
kind: Service
metadata:
  labels:
    app: sample-gs-spring-boot-docker
  name: sample-gs-spring-boot-docker
#  namespace: dex-dev
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: sample-gs-spring-boot-docker